version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: mineflayer
    versions:
    - 3.0.0
    - 3.2.0
    - 3.3.0
    - 3.3.1
    - 3.3.2
    - 3.3.3
    - 3.4.0
